var MSG = {
  title: "Código",
  blocks: "Bloques",
  linkTooltip: "Guarda conexión a los bloques.",
  runTooltip: "Ejecute el programa definido por los bloques en el área de trabajo.",
  badCode: "Error del programa:\n%1",
  timeout: "Se excedio el máximo de iteraciones ejecutadas permitidas.",
  trashTooltip: "Descartar todos los bloques.",
  catLogic: "Lógica",
  catLoops: "Secuencias",
  catMath: "Matemáticas",
  catText: "Texto",
  movements:"movements",
  catLists: "Listas",
  catColour: "Color",
  catVariables: "Variables",
  catFunctions: "Funciones",
  listVariable: "lista",
  textVariable: "texto",
  httpRequestError: "Hubo un problema con la petición.",
  linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
  hashError: "«%1» no corresponde con ningún programa guardado.",
  xmlError: "No se pudo cargar el archivo guardado.  ¿Quizá fue creado con otra versión de Blockly?",
  badXml: "Error de análisis XML:\n%1\n\nSelecciona OK para abandonar tus cambios o Cancelar para seguir editando el XML.",

    /**Toolbox begin*/
    /** toolbox的开始 */
    id_start: "Iniciar",
    /** toolbox的动作 */
    id_actions: "Movimientos",
    /** toolbox的运动 */
    id_moves : "Movimientos",
    /** toolbox的感知 */
    id_sensors : "Sensores",
    /** toolbox的事件 */
    id_events : "Eventos",
    /** toolbox的数学 */
    id_math : "Matemáticas",
    /** toolbox的控制 */
    id_control : "Control",
    /** toolbox的展示 */
    id_show : "Reproducción",
    /**Toolbox end*/

    /**Start Category begin */
    id_when_start : "Hacer clic en \"Ejecutar\" para comenzar",
    id_go_to_start : "Ir a inicio",
    /**Start Category end */

    /** Movement Category begin */
    servo_angle_popup_title :"Establecer ángulo de rotación para servomotor",
    servo_angle_popup_close:"Cerrar",
    servo_angle_popup_variable:"Variable",
    servo_angle_popup_angle:"Ángulo",
    servo_angle_popup_cancel :"Cancelar",
    servo_angle_popup_ok :"Aceptar",

    rotate_servo_popup_clockwise:"En sentido horario",
    rotate_servo_popup_anti_clockwise:"En sentido contrahorario",
    rotate_servo_popup_stop:"detener",
    rotate_servo_popup_title:"Modo de rotación",
    rotate_servo_popup_cancel:"Cancelar",
    rotate_servo_popup_ok:"Aceptar",

    servo_status_popup_title:"Establecer estado del servomotor",
    servo_status_popup_cancel:"Cancelar",
    servo_status_popup_ok:"Aceptar",
    servo_status_popup_locking:"Bloquear",
    servo_status_popup_adjustable:"Desbloquear",
    servo_status_popup_tips:"No es posible ajustar el servomotor correspondiente para el robot cuando el modo bloqueado está activado.",

    posture_named_popup_title :"Introducir un nombre para la posición",
    posture_named_popup_cancel :"Cancelar",
    posture_named_popup_ok :"Aceptar",
    posture_named_popup_placeholder :"Posición",
    posture_named_popup_msg :"El nombre de la posición contiene caracteres no válidos.",
    posture_named_too_long : "El nombre de la posición no debe contener más de %1 caracteres.",
  /*运动  begin*/
    gyro_rotate_direction_popup_title :"Seleccionar dirección de rotación del servomotor",
    gyro_rotate_direction_popup_cancel :"Cancelar",
    gyro_rotate_direction_popup_ok :"Aceptar",
    gyro_rotate_direction_popup_curVal :"Valor actual",
    gyro_rotate_direction_popup_course :"Ángulo acimutal",
    gyro_rotate_direction_popup_horizontal :"Ángulo de giro",
    gyro_rotate_direction_popup_house :"Ángulo de paso",
  /*运动  end*/
    posture_set_desc : "Open the right switch and then move the robot to set the position",
    posture_ok_desc : "Pose after input position name",
    id_servo : 'servomotor',
    id_rotate : 'girar',
    id_degree : 'grado',
    id_in : 'durante',
    id_millsecond : 'ms',

    id_rotate_circle : 'Girar servomotor a 360°',
    id_servos : 'Servomotores',
    id_run_to : 'ejecutar a',
    id_all: 'Todo',
    id_lock : 'bloquear',
    id_unlock : 'desbloquear',
    servo_id : 'Id.',
    servo_angle : 'Ángulo',
    movement_gesture: 'Posición',
    servo_direction : 'dirección',
    servo_speed : 'velocidad',
    /** Movement Category end */

    /**Control Category begin */
    id_control_wait_for : 'esperar a',
    id_control_repeat : 'repetir',
    id_control_repeat_times: 'veces',
    id_control_wait:'esperar',
    id_control_seconds:'segundos',
    id_math_not:'no',
    id_while : 'mientras',
    id_until : 'hasta',
    id_repeat : 'hacer',
    /**Control Category end */

   /*Event Category begin*/
    maincontrol_box :"Caja de control principal",
    low_power :"Batería baja",
    ir_sensor : "Sensor infrarrojo",
    reflectance : "reflectancia",
    touch_sensor:"Sensor táctil",
    status : "el estado es",
    title_touch_sensor : "Configuración de sensor táctil",
    click : "Hacer clic",
    db_click : "Hacer doble clic",
    press_hold : "Mantener presionado",
    release : "Soltar",
    gyroscope : "Giroscopio",
    angle : "ángulo",
    axie : 'eje',
    title_device_tilt : "Configuración de estado de teléfono/panel",
    phone_pad :"Teléfono/panel",
    tilt_left : "Inclinar a la izquierda",
    tilt_right : "Inclinar a la derecha",
    tilt_up : "Inclinar hacia arriba",
    tilt_down : "Inclinar hacia abajo",
    tilt_swing : "Inclinar para balancear",
    /*Event Category end*/

    /** Show Category start */
    id_show_play_effect:'Reproducir efecto',
    id_show_play_tune:'Reproducir tono',
    id_show_show_emoji:'Mostrar emoji',
    id_show_show_LEDs:'Mostrar LED',
    id_show_time_during:'para',
    id_show_time_ms:'ms',
    id_show_times:'veces',
    sound_effects_popup_title :"Establecer efectos de sonido",
    sound_effects_popup_cancel :"Cancelar",
    sound_effects_popup_ok :"Aceptar",
    sound_effects_recording_add :"Agregar nueva grabación",
    sound_effects_recording_delete :"Eliminar",
    title_setting_light : "Estableciendo iluminación",
    title_setting_tune : "Estableciendo tono",
    title_setting_emotion : "Estableciendo emoción",
    id_all_bright: "todo iluminado",
    id_custom: "personalizar",
    id_smile: 'sonreír',
    id_cry : 'llorar',
    id_sad : 'triste',
    id_wink : 'guiño',
    id_dizzy : 'mareado',
    id_daze : 'aturdido',
    id_open_eyes : 'ojos abiertos',
    id_close_eyes : 'ojos cerrados',
    /** Show Category end */

    /**Sensor Category begin */
    id_sensor_IR_sensor: 'Sensor infrarrojo',
    id_sensor_reflectance_between_obstacle:'reflectancia_entre_obstáculo',
    id_sensor_touch_sensor:'Sensor táctil',
    id_sensor_touch_sensor_status:'estado',
    id_sensor_gyroscope:'Giroscopio',
    id_sensor_angle:'ángulo',
    y_axie:'Ángulo de giro',
    x_axie:'Ángulo de paso',
    z_axie:'Ángulo acimutal',
    servo:'Servomotor',
    id_sensor_set_gyroscope:'Establecer giroscopio',
    id_sensor_angle_to_zero:'ángulo a 0',
    /**Sensor Category end */

    /**Math Category begin */
    id_math_variables_set_add : "%1 + %2",
    id_set : "establecer",
    id_to : "a",
    /**Math Category end */

  /* Common section begin */
    btn_name_confirm : "aceptar",
    btn_name_cancel: "cancelar",
  /* Common section end*/
    id_start_info : 'Ejecutar',
    id_stop_info : 'Detener',

    title_infrared_sensor : "Configuración de sensor infrarrojo",
    current_value : 'valor actual',
    distance_1: 'demasiado cerca',
    distance_2:'cerca',
    distance_3:'medio',
    distance_4:'lejos',
    distance_5:'demasiado lejos',

   /* need to be removed, wait to confirm */
    distance_very_near: 'demasiado cerca',
    distance_near:'cerca',
    distance_middle:'medio',
    distance_far:'lejos',
    distance_very_far:'demasiado lejos',

    title_bluetooth_connect : "Conexión Bluetooth",
    title_time_adjust : "Ajuste de hora",

    index_back:"Atrás",
    disconnected : "Desconectado",
  /*项目  begin*/
    //保存项目
    input_rule_msg : "Special characters can not be entered, enter up to %1 characters or %2 chinese characters",
    variable_inputrule_msg : "Can not start with the number, special characters can not be entered, up to %1 characters or %2 chinese characters",
    add_project_placeholder : "Nuevo proyecto",
    project_pop_ok_btn: "Aceptar",
    project_pop_cancel_btn: "Cancelar",
    add_project_pop_title : "Nombre de proyecto",
    add_project_input_check : "Solo se pueden introducir 16 caracteres.",
    project_name_too_long : "El nombre del proyecto no debe superar los %1 caracteres.",
    project_name_popup_msg : "El nombre del proyecto contiene caracteres no válidos.",
    //是否保存项目
    is_add_project_pop_title :"Guardar proyecto",
    is_add_project_pop_tips :"¿Quieres guardar el proyecto actual?",
    //项目列表
    project_list_title :"Mis proyectos",
    porject_alert_title:"Error",
    porject_alert_tips:"Consejos",
    porject_alert_content:"El parámetro de objetivo operativo es incorrecto. Compruébalo.",
    porject_alert_content_01:"El nombre del artículo ya existe. Introduce un nombre de nuevo.",
    porject_alert_content_02:"Se ha producido un error en la operación de servicio base. El mensaje de error es el siguiente:",
    porject_alert_content_03:"Se ha producido un error en los datos recibidos de la base.",
    porject_alert_content_04:"No se ha podido leer el proyecto. ",
    porject_alert_content_05:"El bloque de programa en el archivo del proyecto contiene errores.",
    porject_alert_content_06:"Proyecto guardado",
    porject_alert_btnText:"Aceptar",
   /*项目  end*/
   /*设置音效弹出框音效文件国际化  begin*/
    add_recording_ok:"Aceptar",
    recording_tips:"Grabando",
    id_control_break : 'Fuera de circulación',
    id_blue_disconnect : 'Conexión Bluetooth desconectada',
    id_ok : 'Aceptar',
    recording_title:"Grabando",
    recording_cancel:"Cancelar",
    recording_ok:"Aceptar",
    recording_placeholder:"Introduce un nombre para la grabación.",
    recording_popup_title:"Entrada de nombre del archivo grabado",
    recording_name_popup_msg : "Recording name contains invalid characters",
    animal:"animal",
    machine:"máquina",
    recording:"grabación",
    bear:"oso",
    bird:"pájaro",
    chicken:"pollo",
    cow:"vaca",
    dog:"perro",
    elephant:"elefante",
    giraffe:"jirafa",
    horse:"caballo",
    lion:"león",
    monkey:"mono",
    pig:"cerdo",
    rhinoceros:"rinoceronte",
    sealions:"león marino",
    tiger:"tigre",
    walrus:"morsa",
    ambulance:"ambulancia",
    busy_tone:"tono_ocupado",
    carhorn:"claxon",
    carhorn1:"claxon1",
    doorbell:"timbre",
    engine:"motor",
    laser:"láser",
    meebot:"meebot",
    police_car_1:"coche_policía1",
    police_car_2:"coche_policía2",
    ringtones:"tonos",
    robot:"robot",
    telephone_call:"llamada_telefónica",
    touch_tone:"tono_táctil",
    wave:"ola",
  /*设置音效弹出框音效文件国际化  end*/
    variable_named_popup_placeholder :"Variable",
    title_variable_set : 'Establecer variable',
    variable_named_popup_msg :"El nombre de la variable contiene caracteres no válidos.",
    variable_named_too_long : "El nombre de la variable no debe contener más de %1 caracteres.",
    speed:"velocidad",
    speed_VS:"muy lento",
    speed_S:"lento",
    speed_M:"medio",
    speed_V:"rápido",
    speed_VF:"muy rápido",
    speed_no_value:"Conducción sin ruedas de equipamiento actual",
    speed_only_360_value:"El equipamiento actual no dispone de conducción sin ruedas de 360.",
    lights_tips:"El equipamiento actual no dispone de luces 360.",
    exit_tips:"El programa actual no está guardado, ¿quieres continuar para salir?",
    project_has_no_change:"El programa actual no se ha modificado.",
    close_blue:"La conexión Bluetooth está activada, ¿quieres desactivarla?",
    posture_link:"El modelo no está conectado. Conéctalo primero.",
    posture_link_popup_title:"El modelo está conectado.",
    posture_link_popup_cancel:"cancelar",
    posture_link_popup_ok:"aceptar",
    recording_name_repeat:"Repetición de nombre grabado",
    recording_named_too_long : "El nombre es demasiado largo. Introduce otro más corto.",
    recording_alert_title:"Error",
    recording_alert_content:"error de concesión de privilegio",
    recording_alert_ok:"Aceptar",
    help_title:"Introducción de bloque",
    newProjectName:"Nuevo proyecto",
    sysVoiceName:"voz",
    exit_popup_cancel:"Cancelar",
    exit_popup_ok:"Aceptar",
    exit_popup_title:"Consejos",
    recording_data_tips:"El sistema actual no dispone de archivos de grabación personalizados.",
    infrared_tips:"Infrared sensor is not connected to the current model",
    touch_tips:"The touch sensor is not connected to the current model",
    gyroscope_tips:"The gyro sensor is not connected to the current model",


    id_infinite_loop_error:'Program exit due to out of memory, please return back and retry',
    // 新手指引
    save_project_msg:"Tap here to save your program.",
    projectlist_msg:"See what Jimu have learned and add new program for it.",
    swift_msg:"Tap here to see your code.",
    help_msg:"Need any help? Get support here.",
    run_msg:"Let's run your code on Jimu.",
    go_skip:"skip"

};
