var MSG = {
  title: "コード",
  blocks: "ブロック",
  linkTooltip: "ブロックの状態を保存してリンクを取得します。",
  runTooltip: "ブロックで作成したプログラムを実行します。",
  badCode: "プログラムのエラー:\n%1",
  timeout: "命令の実行回数が制限値を超えました。",
  trashTooltip: "すべてのブロックを消します。",
  catLogic: "論理",
  catLoops: "繰り返し",
  catMath: "数学",
  catText: "テキスト",
  catLists: "リスト",
  catColour: "色",
  catVariables: "変数",
  catFunctions: "関数",
  listVariable: "リスト",
  textVariable: "テキスト",
  httpRequestError: "ネットワーク接続のエラーです。",
  linkAlert: "ブロックの状態をこのリンクで共有できます:\n\n%1",
  hashError: "すみません。「%1」という名前のプログラムは保存されていません。",
  xmlError: "保存されたファイルを読み込めませんでした。別のバージョンのブロックリーで作成された可能性があります。",
  badXml: "XML のエラーです:\n%1\n\nXML の変更をやめるには「OK」、編集を続けるには「キャンセル」を選んでください。",

  /**Toolbox */
  id_start: "開始",
  id_actions: "動き",
  id_moves : "動き",
  id_sensors : "センサー",
  id_events : "イベント",
  id_math : "計算",
  id_control : "コントロール",
  id_show : "表示",

/**Begin Category */
  id_when_start : "「実行」をクリックして開始",
  id_go_to_start : "開始する",

/**Sensor Category */
  id_sensor_IR_sensor: 'IR センサー',
  id_sensor_reflectance_between_obstacle:'障害物間の反射率',
  id_sensor_touch_sensor:'タッチセンサー',
  id_sensor_touch_sensor_status:'ステータス',
  id_sensor_gyroscope:'ジャイロスコープ',
  id_sensor_angle:'角度',
  y_axie:'ロール角',
  x_axie:'ピッチ角',
  z_axie:'ヘディング角',
  servo:'サーボ',
  id_sensor_set_gyroscope:'ジャイロスコープを設定',
  id_sensor_angle_to_zero:'傾き無し',

  id_math_variables_set_add : "%1 + %2",
  id_set : "設定",
  id_to : "設定内容",

  id_control_wait_for : '待機',
  id_control_repeat : '繰り返し',
  id_control_repeat_times: '回数',
  id_control_wait:'待つ',
  id_control_seconds:'数秒',
  id_math_not:'なし',

  /* common section begin */
  btn_name_confirm : "OK",
  btn_name_cancel: "キャンセル",

  /* common section end*/

  /*event component section begin*/
  maincontrol_box :"メインコントロールボックス",
  low_power :"低電力",
  ir_sensor : "IR センサー",
  reflectance : "反射",
  touch_sensor:"タッチセンサー",
  status : "状態",
  title_touch_sensor : "タッチセンサーの設定",
  click : "クリック",
  db_click : "ダブルクリック",
  press_hold : "長押し",
  release : "放す",
  gyroscope : "ジャイロスコープ",
  angle : "角度",
  axie : '軸',
  title_device_tilt : "携帯電話/パッドステータスの設定",
  phone_pad :"携帯電話/パッド",
  tilt_left : "左に傾ける",
  tilt_right : "右に傾ける",
  tilt_up : "上に傾ける",
  tilt_down : "下に傾ける",
  tilt_swing : "傾けてスイング",
  /*event component section end*/

  /** control  */
  id_while : '期間',
  id_until : '範囲',
  id_repeat : '実行する',

  id_start_info : '実行',
  id_stop_info : '停止',

  title_infrared_sensor : "赤外線センサーの設定",
  current_value : '現在の値',
  distance_1: '近すぎ',
  distance_2:'近い',
  distance_3:'中間',
  distance_4:'遠い',
  distance_5:'遠すぎ',

  /* need to be removed, wait to confirm */
  distance_very_near: '近すぎ',
  distance_near:'近い',
  distance_middle:'中間',
  distance_far:'遠い',
  distance_very_far:'遠すぎ',

  id_servo : 'サーボ',
  id_rotate : '回転',
  id_degree : '度',
  id_in : '間',
  id_millsecond : 'ミリ秒',

  id_rotate_circle : 'サーボを 360°回転させる',
  id_servos : 'サーボ',
  id_run_to : '移動先',

  /* display section begin */
  title_setting_light : "ライトの設定",
  title_setting_tune : "チャンネルの設定",
  title_setting_emotion : "感情の設定",
  id_all_bright: "すべて点灯",
  id_custom: "カスタム",
  id_smile: '微笑む',
  id_cry : '泣く',
  id_sad : '悲しむ',
  id_wink : 'ウィンクする',
  id_dizzy : '混乱する',
  id_daze : 'ボーっとする',
  id_open_eyes : '目を開ける',
  id_close_eyes : '目を閉じる',
  /* display section end */

  id_all: 'すべて',
  id_lock : 'ロック',
  id_unlock : 'ロック解除',

  title_bluetooth_connect : "Bluetooth 接続",
  title_time_adjust : "時間調整",

  // Show
  id_show_play_effect:'プレイエフェクト',
  id_show_play_tune:'曲を演奏する',
  id_show_show_emoji:'絵文字を表示する',
  id_show_show_LEDs:'LED を点灯する',
  id_show_time_during:'間',
  id_show_time_ms:'ミリ秒',
  id_show_times:'回数',
    /*展示  begin*/
  sound_effects_popup_title :"音響の設定",
  sound_effects_popup_cancel :"キャンセル",
  sound_effects_popup_ok :"OK",
  sound_effects_recording_add :"新しい記録を追加",
  sound_effects_recording_delete :"削除",

  servo_id : 'ID',
  servo_angle : '角度',
  movement_gesture: 'ポーズ', 
  servo_direction : '向き',
  servo_speed : '速度',

    /*展示  end*/

    /*运动  begin*/
  servo_angle_popup_title :"サーボモーターの回転角度を設定",
  servo_angle_popup_close:"閉じる",
  servo_angle_popup_variable:"変数",
  servo_angle_popup_angle:"角度",
  servo_angle_popup_cancel :"キャンセル",
  servo_angle_popup_ok :"OK",

  rotate_servo_popup_clockwise:"時計回り",
  rotate_servo_popup_anti_clockwise:"反時計回り",
  rotate_servo_popup_stop:"停止",
  rotate_servo_popup_title:"回転モード",
  rotate_servo_popup_cancel:"キャンセル",
  rotate_servo_popup_ok:"OK",

  servo_status_popup_title:"サーボモーターのステータスを設定",
  servo_status_popup_cancel:"キャンセル",
  servo_status_popup_ok:"OK",
  servo_status_popup_locking:"ロック",
  servo_status_popup_adjustable:"ロック解除",
  servo_status_popup_tips:"ロックモードの場合は、ロボットの対応サーボを調整できません。",

    posture_named_popup_title :"ポーズに名前を付ける",
    posture_named_popup_cancel :"キャンセル",
    posture_named_popup_ok :"OK",
    posture_named_popup_placeholder :"ポーズ",
    posture_named_popup_msg :"ポーズ名に不正文字が含まれています",
    posture_named_too_long : "ポーズ名が %1文字を超えないようにしてください",

    gyro_rotate_direction_popup_title :"サーボモーターの回転方向を選択します",
    gyro_rotate_direction_popup_cancel :"キャンセル",
    gyro_rotate_direction_popup_ok :"OK",
    gyro_rotate_direction_popup_curVal :"現在の値",
    gyro_rotate_direction_popup_course :"ヘディング角",
    gyro_rotate_direction_popup_horizontal :"ロール角",
    gyro_rotate_direction_popup_house :"ピッチ角",


    /*运动  end*/
    index_back:"戻る",
    disconnected : "切断済み",

    /*项目  begin*/
    //保存项目
    add_project_placeholder : "新規のプロジェクト",
    project_pop_ok_btn: "OK",
    project_pop_cancel_btn: "キャンセル",
    add_project_pop_title : "プロジェクト名",
    add_project_input_check : "16文字のみ入力可能",
    project_name_too_long : "プロジェクト名が %1文字を超えないようにしてください",
    project_name_popup_msg : "プロジェクト名に不正文字が含まれています",
    //是否保存项目
    is_add_project_pop_title :"プロジェクトを保存",
    is_add_project_pop_tips :"現在のプロジェクトを保存しますか？",
    //项目列表
    project_list_title :"マイプロジェクト",
    porject_alert_title:"エラー",
    porject_alert_tips:"ヒント",
    porject_alert_content:"申し訳ありませんが、操作対象のパラメータが間違っています。確認してください。",
    porject_alert_content_01:"アイテム名はすでに存在します。もう一度入力してください。",
    porject_alert_content_02:"ベースサービス操作のエラーです。エラーメッセージ：",
    porject_alert_content_03:"ベースから受信したデータにエラーがあります。",
    porject_alert_content_04:"プロジェクトを読み取れませんでした ",
    porject_alert_content_05:"申し訳ありませんが、プロジェクトファイルのプログラムブロックにエラーがあります。",
    porject_alert_content_06:"保存済みのプロジェクト",
    porject_alert_btnText:"OK",
    /*项目  end*/
    add_recording_ok:"OK",
    recording_tips:"記録",
    id_control_break : '循環範囲外',
    id_blue_disconnect : 'Bluetooth が接続されていません',
    id_ok : 'OK',
    recording_title:"記録",
    recording_cancel:"キャンセル",
    recording_ok:"OK",
    recording_placeholder:"記録名を入力してください",
    recording_popup_title:"記録されたファイル名の入力",
    /*项目  end*/
    /*设置音效弹出框音效文件国际化  begin*/
    animal:"動物",
    machine:"機械",
    recording:"記録",
    bear:"熊",
    bird:"鳥",
    chicken:"ニワトリ",
    cow:"牛",
    dog:"犬",
    elephant:"象",
    giraffe:"キリン",
    horse:"馬",
    lion:"ライオン",
    monkey:"猿",
    pig:"豚",
    rhinoceros:"サイ",
    sealions:"アシカ",
    tiger:"トラ",
    walrus:"セイウチ",
    ambulance:"救急車",
    busy_tone:"ビジートーン",
    carhorn:"車のクラクション",
    carhorn1:"車のクラクション 1",
    doorbell:"呼び鈴",
    engine:"エンジン",
    laser:"レーザー",
    meebot:"Meebot",
    police_car_1:"パトカー 1",
    police_car_2:"パトカー 2",
    ringtones:"着信音",
    robot:"ロボット",
    telephone_call:"電話",
    touch_tone:"プッシュ音",
    wave:"手を振る",
    /*设置音效弹出框音效文件国际化  end*/

    variable_named_popup_placeholder :"変数",
    title_variable_set : '変数の設定',
    variable_named_popup_msg :"変数名に不正文字が含まれています",
    variable_named_too_long : "変数名が %1文字を超えないようにしてください",
    speed:"速度",
    speed_VS:"とても遅い",
    speed_S:"遅い",
    speed_M:"普通",
    speed_V:"速い",
    speed_VF:"とても速い",
    speed_no_value:"現在の装置はホイールレスステアリングです",
    speed_only_360_value:"現在の装置に360ホイールレスステアリングはありません",
    lights_tips:"現在の装置に360ライトはありません",
    exit_tips:"現在のプログラムは保存されていません。終了を続行しますか？",
    project_has_no_change:"現在のプログラムは変更されていません",
    close_blue:"Bluetooth が接続されていません。切断されていませんか？",
    posture_link:"モデルが接続されていません。まずモデルを接続してください",
    posture_link_popup_title:"モデルを接続",
    posture_link_popup_cancel:"キャンセル",
    posture_link_popup_ok:"OK",
    recording_name_repeat:"記録した名前の重複",
    recording_named_too_long : "名前が長すぎます。もう一度入力してください。",
    recording_alert_title:"エラー",
    recording_alert_content:"特典を付与できませんでした",
    recording_alert_ok:"OK",
    help_title:"ブロックの導入",
    newProjectName:"新規のプロジェクト",
    sysVoiceName:"音声",
    exit_popup_cancel:"キャンセル",
    exit_popup_ok:"OK",
    exit_popup_title:"ヒント",
    recording_data_tips:"現在のシステムにはカスタム記録ファイルがありません",
  //需新录入翻译
  movements:"movements",
  posture_set_desc : "Open the right switch and then move the robot to set the position",
  posture_ok_desc : "Pose after input position name",
  //保存项目
  input_rule_msg : "Special characters can not be entered, enter up to %1 characters or %2 chinese characters",
  variable_inputrule_msg : "Can not start with the number, special characters can not be entered, up to %1 characters or %2 chinese characters",
  recording_name_popup_msg : "Recording name contains invalid characters",
  infrared_tips:"Infrared sensor is not connected to the current model",
  touch_tips:"The touch sensor is not connected to the current model",
  gyroscope_tips:"The gyro sensor is not connected to the current model",
  id_infinite_loop_error:'Program exit due to out of memory, please return back and retry',
  // 新手指引
  save_project_msg:"Tap here to save your program.",
  projectlist_msg:"See what Jimu have learned and add new program for it.",
  swift_msg:"Tap here to see your code.",
  help_msg:"Need any help? Get support here.",
  run_msg:"Let's run your code on Jimu.",
  go_skip:"skip"
};
