var MSG = {
  title: "Код",
  blocks: "Блокчиња",
  linkTooltip: "Зачувај и стави врска до блокчињата.",
  runTooltip: "Пушти го програмот определен од блокчињата во работниот простор.",
  badCode: "Грешка во програмот:\n%1",
  timeout: "Го надминавте допуштениот број на повторувања во извршувањето.",
  trashTooltip: "Отстрани ги сите блокчиња.",
  catLogic: "Логика",
  catLoops: "Јамки",
  catMath: "Математика",
  catText: "Текст",
  catLists: "Списоци",
  catColour: "Боја",
  catVariables: "Променливи",
  catFunctions: "Функции",
  listVariable: "список",
  textVariable: "текст",
  httpRequestError: "Се појави проблем во барањето.",
  linkAlert: "Споделете ги вашите блокчиња со оваа врска:\n\n%1",
  hashError: "„%1“ не одговара на ниеден зачуван програм.",
  xmlError: "Не можев да ја вчитам зачуваната податотека. Да не сте ја создале со друга верзија на Blockly?",
  badXml: "Грешка при расчленувањето на XML:\n%1\n\nСтиснете на „ОК“ за да ги напуштите промените или на „Откажи“ ако сакате уште да ја уредувате XML-податотеката.",
  //以下部分需要新录入翻译
  movements:"movements",
  /**Toolbox begin*/
  /** toolbox的开始 */
  id_start: "Start",
  /** toolbox的动作 */
  id_actions: "Moves",
  /** toolbox的运动 */
  id_moves : "Moves",
  /** toolbox的感知 */
  id_sensors : "Sensors",
  /** toolbox的事件 */
  id_events : "Events",
  /** toolbox的数学 */
  id_math : "Math",
  /** toolbox的控制 */
  id_control : "Control",
  /** toolbox的展示 */
  id_show : "Show",
  /**Toolbox end*/
  /**Start Category begin */
  id_when_start : "Click 'Run' to start",
  id_go_to_start : "Go to start",
  /**Start Category end */
  /** Movement Category begin */
  servo_angle_popup_title :"Set rotation angle for servo motor",
  servo_angle_popup_close:"Close",
  servo_angle_popup_variable:"Variable",
  servo_angle_popup_angle:"Angle",
  servo_angle_popup_cancel :"Cancel",
  servo_angle_popup_ok :"OK",

  rotate_servo_popup_clockwise:"Clockwise",
  rotate_servo_popup_anti_clockwise:"Anti-clockwise",
  rotate_servo_popup_stop:"stop",
  rotate_servo_popup_title:"Rotating Mode",
  rotate_servo_popup_cancel:"Cancel",
  rotate_servo_popup_ok:"OK",

  servo_status_popup_title:"Set status of servo motor",
  servo_status_popup_cancel:"Cancel",
  servo_status_popup_ok:"OK",
  servo_status_popup_locking:"Lock",
  servo_status_popup_adjustable:"Unlock",
  servo_status_popup_tips:"You cannot adjust the corresponding servo for the robot when in locked mode",

  posture_named_popup_title :"Name the action",
  posture_named_popup_cancel :"Cancel",
  posture_named_popup_ok :"OK",
  posture_named_popup_placeholder :"Action",
  posture_named_popup_msg :"Action name contains illegal characters",
  posture_named_too_long : "Action name could not exceed %1 characters",

  gyro_rotate_direction_popup_title :"Select rotation direction for servo motor",
  gyro_rotate_direction_popup_cancel :"Cancel",
  gyro_rotate_direction_popup_ok :"OK",
  gyro_rotate_direction_popup_curVal :"Current value",
  gyro_rotate_direction_popup_course :"Heading angle",
  gyro_rotate_direction_popup_horizontal :"Roll angle",
  gyro_rotate_direction_popup_house :"Pitch angle",

  posture_set_desc : "Open the right switch and then move the robot to set the position",
  posture_ok_desc : "Pose after input position name",

  id_servo : 'Servo',
  id_rotate : 'rotate',
  id_degree : 'degree',
  id_in : 'during',
  id_millsecond : 'ms',

  id_rotate_circle : 'Rotate servo 360°',
  id_servos : 'Rotate servos',
  id_run_to : 'Run to',
  id_all: 'All',
  id_lock : 'lock',
  id_unlock : 'unlock',

  servo_id : 'ID',
  servo_angle : 'Angle',
  movement_gesture: 'Action',
  servo_direction : 'direction',
  servo_speed : 'speed',
  /** Movement Category end */

  /**Control Category begin */
  id_control_wait_for : 'wait for',
  id_control_repeat : 'repeat',
  id_control_repeat_times: 'times',
  id_control_wait:'wait',
  id_control_seconds:'seconds',
  id_math_not:'not',
  id_while : 'while',
  id_until : 'until',
  id_repeat : 'repeat',
  /**Control Category end */

  /*Event Category begin*/
  maincontrol_box :"Maincontrol box",
  low_power :"Low power",
  ir_sensor : "IR Sensor",
  reflectance : "reflectance",
  touch_sensor:"Touch sensor",
  status : "status is",
  title_touch_sensor : "Touch sensor setting",
  click : "Click",
  db_click : "Double Click",
  press_hold : "Press Hold",
  release : "Release",
  gyroscope : "Gyroscope",
  angle : "angle",
  axie : 'axie',
  title_device_tilt : "Phone/Tablet status setting",
  phone_pad :"Phone/Tablet",
  tilt_left : "Tilt left",
  tilt_right : "Tilt right",
  tilt_up : "Tilt up",
  tilt_down : "Tilt down",
  tilt_swing : "Tilt swing",
  /*Event Category end*/

  /** Show Category start */
  id_show_play_effect:'Play effect',
  id_show_play_tune:'Play tune',
  id_show_show_emoji:'Show emoji',
  id_show_show_LEDs:'Show LEDs',
  id_show_time_during:'for',
  id_show_time_ms:'ms',
  id_show_times:'times',
  sound_effects_popup_title :"Set sound effects",
  sound_effects_popup_cancel :"Cancel",
  sound_effects_popup_ok :"OK",
  sound_effects_recording_add :"Add new recording",
  sound_effects_recording_delete :"Delete",
  title_setting_light : "Setting Light",
  title_setting_tune : "Setting Tune",
  title_setting_emotion : "Setting Emotion",
  id_all_bright: "all bright",
  id_custom: "custom",
  id_smile: 'smile',
  id_cry : 'cry',
  id_sad : 'sad',
  id_wink : 'wink',
  id_dizzy : 'dizzy',
  id_daze : 'daze',
  id_open_eyes : 'open eyes',
  id_close_eyes : 'close eyes',
  /** Show Category end */

  /**Sensor Category begin */
  id_sensor_IR_sensor: 'IR sensor',
  id_sensor_reflectance_between_obstacle:'reflectance between obstacle',
  id_sensor_touch_sensor:'Touch sensor',
  id_sensor_touch_sensor_status:'status',
  id_sensor_gyroscope:'Gyroscope',
  id_sensor_angle:'angle',
  y_axie:'Pitch angle',
  x_axie:'Roll angle',
  z_axie:'Heading angle',
  servo:'Servo',
  id_sensor_set_gyroscope:'Set gyroscope',
  id_sensor_angle_to_zero:'all angle to zero degrees',
  /**Sensor Category end */

  /**Math Category begin */
  id_math_variables_set_add : "%1 + %2",
  id_set : "set",
  id_to : "to",
  /**Math Category end */

  /* Common section begin */
  btn_name_confirm : "ok",
  btn_name_cancel: "cancel",
  /* Common section end*/

  id_start_info : 'Run',
  id_stop_info : 'Stop',

  title_infrared_sensor : "Infrared Sensor Setting",
  current_value : 'current value',
  distance_1: 'too near',
  distance_2:'near',
  distance_3:'middle',
  distance_4:'far',
  distance_5:'too far',

  /* need to be removed, wait to confirm */
  distance_very_near: 'too near',
  distance_near:'near',
  distance_middle:'middle',
  distance_far:'far',
  distance_very_far:'too far',

  title_bluetooth_connect : "Bluetooth Connect",
  title_time_adjust : "Time Adjust",

  index_back:"Back",
  disconnected : "Disconnected",

  /*项目  begin*/
  //保存项目
  input_rule_msg : "Special characters can not be entered, enter up to %1 characters or %2 chinese characters",
  variable_inputrule_msg : "Can not start with the number, special characters can not be entered, up to %1 characters or %2 chinese characters",
  add_project_placeholder : "Project name",
  project_pop_ok_btn: "OK",
  project_pop_cancel_btn: "Cancel",
  add_project_pop_title : "Project name",
  add_project_input_check : "Can only enter 16 characters",
  project_name_too_long : "Project name could not exceed %1 characters",
  project_name_popup_msg : "Project name contains invalid characters",
  //是否保存项目
  is_add_project_pop_title :"Save project",
  is_add_project_pop_tips :"Save current project?",
  //项目列表
  project_list_title :"My Projects",
  porject_alert_title:"Error",
  porject_alert_tips:"Tips",
  porject_alert_content:"Sorry, wrong parameter for operating target. Please check!",
  porject_alert_content_01:" Item name already exists. Please enter again.",
  porject_alert_content_02:" Error in base service operation. The error message is:",
  porject_alert_content_03:" Error in data received from base!",
  porject_alert_content_04:" Failed to read project ",
  porject_alert_content_05:" Sorry, the program block in the project file contains errors!",
  porject_alert_content_06:"Project saved",
  porject_alert_btnText:"OK",
  /*项目  end*/
  /*设置音效弹出框音效文件国际化  begin*/
  add_recording_ok:"OK",
  recording_tips:"Recording",
  id_control_break : 'Out of circulation',
  id_blue_disconnect : 'Bluetooth is not connected',
  id_ok : 'OK',
  recording_title:"Recording",
  recording_cancel:"Canncel",
  recording_ok:"OK",
  recording_placeholder:"Please enter a recording name",
  recording_popup_title:"Recorded file name input",
  recording_name_popup_msg : "Recording name contains invalid characters",
  animal:"animal",
  machine:"machine",
  recording:"recording",
  bear:"bear",
  bird:"bird",
  chicken:"chicken",
  cow:"cow",
  dog:"dog",
  elephant:"elephant",
  giraffe:"giraffe",
  horse:"horse",
  lion:"lion",
  monkey:"monkey",
  pig:"pig",
  rhinoceros:"rhinoceros",
  sealions:"sealions",
  tiger:"tiger",
  walrus:"walrus",
  ambulance:"ambulance",
  busy_tone:"busy_tone",
  carhorn:"carhorn",
  carhorn1:"carhorn1",
  doorbell:"doorbell",
  engine:"engine",
  laser:"laser",
  meebot:"meebot",
  police_car_1:"police_car_1",
  police_car_2:"police_car_2",
  ringtones:"ringtones",
  robot:"robot",
  telephone_call:"telephone_call",
  touch_tone:"touch_tone",
  wave:"wave",
  /*设置音效弹出框音效文件国际化  end*/

  variable_named_popup_placeholder :"Variable",
  title_variable_set : 'Set Variable',
  variable_named_popup_msg :"variable name contains illegal characters",
  variable_named_too_long : "variable name could not exceed %1 characters",
  speed:"speed",
  speed_VS:"very slow",
  speed_S:"slow",
  speed_M:"middle",
  speed_V:"fast",
  speed_VF:"very fast",
  speed_no_value:"Current equipment wheelless steering",
  speed_only_360_value:"Current equipment has no 360 wheelless steering",
  lights_tips:"Current equipment has no 360 lights",
  exit_tips:"The current program is not saved, whether to continue to exit？",
  project_has_no_change:"The current program has not changed",
  close_blue:"Bluetooth is connected, it does disconnect?",
  posture_link:"The model is not connected. Please connect the model first",
  posture_link_popup_title:"The model connect",
  posture_link_popup_cancel:"cancel",
  posture_link_popup_ok:"ok",
  recording_name_repeat:"Recorded Name Repeat",
  recording_named_too_long : "The name is too long, please input again",
  recording_alert_title:"Error",
  recording_alert_content:"privilege grant failed",
  recording_alert_ok:"OK",
  help_title:"Block introduction",
  newProjectName:"NewProject",
  sysVoiceName:"voice",
  exit_popup_cancel:"Cancel",
  exit_popup_ok:"OK",
  exit_popup_title:"Tips",
  recording_data_tips:"No records",
  infrared_tips:"Infrared sensor is not connected to the current model",
  touch_tips:"The touch sensor is not connected to the current model",
  gyroscope_tips:"The gyro sensor is not connected to the current model",
  id_infinite_loop_error:'Program exit due to out of memory, please return back and retry',
  // 新手指引
  save_project_msg:"Tap here to save your program.",
  projectlist_msg:"See what Jimu have learned and add new program for it.",
  swift_msg:"Tap here to see your code.",
  help_msg:"Need any help? Get support here.",
  run_msg:"Let's run your code on Jimu.",
  go_skip:"skip"
};
