var MSG = {
  title: "Код",
  blocks: "Блоки",
  linkTooltip: "Сохранить и показать ссылку на блоки.",
  runTooltip: "Запустить программу, заданную блоками в рабочей области.",
  badCode: "Ошибка программы:\n%1",
  timeout: "Превышено максимальное количество итераций.",
  trashTooltip: "Удалить все блоки.",
  catLogic: "Логические",
  catLoops: "Циклы",
  catMath: "Математика",
  catText: "Текст",
  catLists: "Списки",
  catColour: "Цвет",
  catVariables: "Переменные",
  catFunctions: "Функции",
  listVariable: "список",
  textVariable: "текст",
  httpRequestError: "Произошла проблема при запросе.",
  linkAlert: "Поделитесь своими блоками по этой ссылке:\n\n%1",
  hashError: "К сожалению, «%1» не соответствует ни одному сохраненному файлу Блокли.",
  xmlError: "Не удалось загрузить ваш сохраненный файл.  Возможно, он был создан в другой версии Блокли?",
  badXml: "Ошибка синтаксического анализа XML:\n%1\n\nВыберите 'ОК', чтобы отказаться от изменений или 'Cancel' для дальнейшего редактирования XML.",

  /**Toolbox begin*/
  /** toolbox的开始 */
  id_start: "Пуск",
  /** toolbox的动作 */
  id_actions: "Движения",
  /** toolbox的运动 */
  id_moves : "Движения",
  /** toolbox的感知 */
  id_sensors : "Датчики",
  /** toolbox的事件 */
  id_events : "События",
  /** toolbox的数学 */
  id_math : "Математика",
  /** toolbox的控制 */
  id_control : "Управление",
  /** toolbox的展示 */
  id_show : "Показать",
  /**Toolbox end*/

  /**Start Category begin */
  id_when_start : "Щелкните «Запуск» для запуска",
  id_go_to_start : "Перейти в Пуск",
  /**Start Category end */
  
  /** Movement Category begin */
  servo_angle_popup_title :"Установить угол вращения сервопривода",
  servo_angle_popup_close:"Закрыть",
  servo_angle_popup_variable:"Переменная",
  servo_angle_popup_angle:"Угол",
  servo_angle_popup_cancel :"Отмена",
  servo_angle_popup_ok :"ОК",

  rotate_servo_popup_clockwise:"По часовой стрелке",
  rotate_servo_popup_anti_clockwise:"Против часовой стрелки",
  rotate_servo_popup_stop:"остановка",
  rotate_servo_popup_title:"Режим вращения",
  rotate_servo_popup_cancel:"Отмена",
  rotate_servo_popup_ok:"ОК",

  servo_status_popup_title:"Установить состояние сервопривода",
  servo_status_popup_cancel:"Отмена",
  servo_status_popup_ok:"ОК",
  servo_status_popup_locking:"Заблокировать",
  servo_status_popup_adjustable:"Разблокировать",
  servo_status_popup_tips:"Невозможно регулировать соответствующий сервопривод для робота в заблокированном режиме",

  posture_named_popup_title :"Название позы",
  posture_named_popup_cancel :"Отмена",
  posture_named_popup_ok :"ОК",
  posture_named_popup_placeholder :"Поза",
  posture_named_popup_msg :"Название позы содержит недопустимые символы",
  posture_named_too_long : "Длина названия позы не может превышать %1 символов",

  gyro_rotate_direction_popup_title :"Выберите направление вращения сервопривода",
  gyro_rotate_direction_popup_cancel :"Отмена",
  gyro_rotate_direction_popup_ok :"ОК",
  gyro_rotate_direction_popup_curVal :"Текущее значение",
  gyro_rotate_direction_popup_course :"Угол курса",
  gyro_rotate_direction_popup_horizontal :"Угол вращения",
  gyro_rotate_direction_popup_house :"Угол наклона",

  id_servo : 'сервопривод',
  id_rotate : 'вращать',
  id_degree : 'угол',
  id_in : 'в течение',
  id_millsecond : 'мс',

  id_rotate_circle : 'Вращать сервопривод на 360°',
  id_servos : 'сервоприводы',
  id_run_to : 'запуск до',
  id_all: 'Все',
  id_lock : 'заблокировать',
  id_unlock : 'разблокировать',

  servo_id : 'Идентификатор',
  servo_angle : 'Угол',
  movement_gesture: 'Поза', 
  servo_direction : 'направление',
  servo_speed : 'скорость',
  /** Movement Category end */

  /**Control Category begin */
  id_control_wait_for : 'ожидать',
  id_control_repeat : 'повторить',
  id_control_repeat_times: 'раз',
  id_control_wait:'ожидание',
  id_control_seconds:'секунд',
  id_math_not:'не',
  id_while : 'по мере того, как',
  id_until : 'до тех пор, пока',
  id_repeat : 'выполнять',
  /**Control Category end */

  /*Event Category begin*/
  maincontrol_box :"Основной блок управления",
  low_power :"Низкий уровень заряда",
  ir_sensor : "ИК-датчик",
  reflectance : "коэффициент отражения",
  touch_sensor:"Датчик касания",
  status : "состояние",
  title_touch_sensor : "Установка датчика касания",
  click : "Щелчок",
  db_click : "Двойной щелчок",
  press_hold : "Нажмите Hold",
  release : "Выпустить",
  gyroscope : "Гироскоп",
  angle : "угол",
  axie : 'axie',
  title_device_tilt : "Настройка состояния телефона / планшета",
  phone_pad :"Телефон / планшет",
  tilt_left : "Наклон влево",
  tilt_right : "Наклон вправо",
  tilt_up : "Наклон вверх",
  tilt_down : "Наклон вниз",
  tilt_swing : "Наклон качения",
  /*Event Category end*/

  /** Show Category start */
  id_show_play_effect:'Воспроизвести эффект',
  id_show_play_tune:'Воспроизвести мелодию',
  id_show_show_emoji:'Показать эмодзи',
  id_show_show_LEDs:'Показать светодиодные индикаторы',
  id_show_time_during:'на',
  id_show_time_ms:'мс',
  id_show_times:'раз',
  sound_effects_popup_title :"Установить звуковые эффекты",
  sound_effects_popup_cancel :"Отмена",
  sound_effects_popup_ok :"ОК",
  sound_effects_recording_add :"Добавить новую запись",
  sound_effects_recording_delete :"Удалить",
  title_setting_light : "Настройка Света",
  title_setting_tune : "Настройка Мелодии",
  title_setting_emotion : "Настройка Эмоции",
  id_all_bright: "все ярко",
  id_custom: "пользовательская",
  id_smile: 'улыбка',
  id_cry : 'плачь',
  id_sad : 'грусть',
  id_wink : 'подмигивание',
  id_dizzy : 'головокружение',
  id_daze : 'изумление',
  id_open_eyes : 'открыть глаза',
  id_close_eyes : 'закрыть глаза',
  /** Show Category end */

  /**Sensor Category begin */
  id_sensor_IR_sensor: 'ИК-датчик',
  id_sensor_reflectance_between_obstacle:'reflectance_between_obstacle',
  id_sensor_touch_sensor:'Датчик касания',
  id_sensor_touch_sensor_status:'состояние',
  id_sensor_gyroscope:'Гироскоп',
  id_sensor_angle:'угол',
  y_axie:'Угол вращения',
  x_axie:'Угол наклона',
  z_axie:'Угол курса',
  servo:'Сервопривод',
  id_sensor_set_gyroscope:'Установить гироскоп',
  id_sensor_angle_to_zero:'угол на 0',
  /**Sensor Category end */
  
  /**Math Category begin */
  id_math_variables_set_add : "%1 + %2",
  id_set : "установить",
  id_to : "на",
  /**Math Category end */

  /* Common section begin */
  btn_name_confirm : "ок",
  btn_name_cancel: "отмена",
  /* Common section end*/
  
  id_start_info : 'Запуск',
  id_stop_info : 'Остановка',

  title_infrared_sensor : "Настройка инфракрасного датчика",
  current_value : 'текущее значение',
  distance_1: 'слишком близко',
  distance_2:'близко',
  distance_3:'средне',
  distance_4:'далеко',
  distance_5:'слишком далеко',

  /* need to be removed, wait to confirm */
  distance_very_near: 'слишком близко',
  distance_near:'близко',
  distance_middle:'средне',
  distance_far:'далеко',
  distance_very_far:'слишком далеко',

  title_bluetooth_connect : "Соединение Bluetooth",
  title_time_adjust : "Регулировка времени",

    index_back:"Назад",
    disconnected : "Отключено",

    /*项目  begin*/
    //保存项目
    add_project_placeholder : "Новый проект",
    project_pop_ok_btn: "ОК",
    project_pop_cancel_btn: "Отмена",
    add_project_pop_title : "Имя проекта",
    add_project_input_check : "Можно ввести только 16 символов",
    project_name_too_long : "Длина имени проекта не может превышать %1 символов",
    project_name_popup_msg : "Имя проекта содержит недопустимые символы",
    //是否保存项目
    is_add_project_pop_title :"Сохранить проект",
    is_add_project_pop_tips :"Сохранить текущий проект?",
    //项目列表
    project_list_title :"Мои проекты",
    porject_alert_title:"Ошибка",
    porject_alert_tips:"Советы",
    porject_alert_content:"Извините, неверный параметр для рабочей цели. Пожалуйста проверьте!",
    porject_alert_content_01:"Название элемента уже существует. Повторите ввод.",
    porject_alert_content_02:"Ошибка в базовой операции обслуживания. Сообщение ошибки:",
    porject_alert_content_03:"Ошибка в данных, полученных из базы!",
    porject_alert_content_04:"Не удалось прочитать проект ",
    porject_alert_content_05:"Извините, блок программы в файле проекта содержит ошибки!",
    porject_alert_content_06:"Проект сохранен",
    porject_alert_btnText:"ОК",
    /*项目  end*/
    add_recording_ok:"ОК",
    recording_tips:"Запись",
    id_control_break : 'Изъято из обращения',
    id_blue_disconnect : 'Bluetooth не подключен',
    id_ok : 'ОК',
    recording_title:"Запись",
    recording_cancel:"Отмена",
    recording_ok:"ОК",
    recording_placeholder:"Введите название записи",
    recording_popup_title:"Ввод названия записанного файла",
    /*项目  end*/
    /*设置音效弹出框音效文件国际化  begin*/
    animal:"животное",
    machine:"машина",
    recording:"запись",
    bear:"медведь",
    bird:"птица",
    chicken:"курица",
    cow:"корова",
    dog:"собака",
    elephant:"слон",
    giraffe:"жираф",
    horse:"лошадь",
    lion:"лев",
    monkey:"обезьяна",
    pig:"свинья",
    rhinoceros:"носорог",
    sealions:"морские львы",
    tiger:"тигр",
    walrus:"морж",
    ambulance:"скорая помощь",
    busy_tone:"busy_tone",
    carhorn:"сигнал автомобиля",
    carhorn1:"carhorn1",
    doorbell:"дверной звонок",
    engine:"двигатель",
    laser:"лазер",
    meebot:"мибот",
    police_car_1:"police_car_1",
    police_car_2:"police_car_2",
    ringtones:"мелодии звонка",
    robot:"робот",
    telephone_call:"telephone_call",
    touch_tone:"touch_tone",
    wave:"волна",
    /*设置音效弹出框音效文件国际化  end*/

    variable_named_popup_placeholder :"Переменная",
    title_variable_set : 'Задать переменную',
    variable_named_popup_msg :"Имя переменной содержит недопустимые символы",
    variable_named_too_long : "Длина имени переменной не может превышать %1 символов",
    speed:"скорость",
    speed_VS:"очень медленно",
    speed_S:"медленно",
    speed_M:"средне",
    speed_V:"быстро",
    speed_VF:"очень быстро",
    speed_no_value:"Текущее оборудование имеет руление без колес",
    speed_only_360_value:"Текущее оборудование не имеет 360 руления без колес",
    lights_tips:"Текущее оборудование не имеет 360 огней",
    exit_tips:"Текущая программа не сохранена, продолжить выход？",
    project_has_no_change:"Текущая программа не изменена",
    close_blue:"Bluetooth подключен, отключить?",
    posture_link:"Модель не подключена. Сначала подключите модель",
    posture_link_popup_title:"Модель подключена",
    posture_link_popup_cancel:"отмена",
    posture_link_popup_ok:"ок",
    recording_name_repeat:"Повтор названия записи",
    recording_named_too_long : "Слишком длинное название, введите заново",
    recording_alert_title:"Ошибка",
    recording_alert_content:"Сбой предоставления привилегий",
    recording_alert_ok:"ОК",
    help_title:"Введение блока",
    newProjectName:"NewProject",
    sysVoiceName:"голос",
    exit_popup_cancel:"Отмена",
    exit_popup_ok:"ОК",
    exit_popup_title:"Советы",
    recording_data_tips:"Текущая система не имеет пользовательских файлов записи"
};
