var MSG = {
  title: "代码",
  blocks: "块",
  linkTooltip: "保存模块并生成链接。",
  runTooltip: "于工作区中运行块所定义的程式。",
  badCode: "程序错误：\n%1",
  timeout: "超过最大执行行数。",
  trashTooltip: "放弃所有块。",
  catLogic: "逻辑",
  catLoops: "循环",
  catMath: "数学",
  catText: "文本",
  catLists: "列表",
  catColour: "颜色",
  catVariables: "变量",
  catFunctions: "函数",
  listVariable: "列表",
  textVariable: "文本",
  httpRequestError: "请求存在问题。",
  linkAlert: "通过这个链接分享您的模块：\n\n%1",
  hashError: "对不起，没有任何已保存的程序对应'%1' 。",
  xmlError: "无法载入您保存的文件。您是否使用其他版本的Blockly创建该文件的？",
  badXml: "XML解析错误：\n%1\n\n选择“确定”以取消您对XML的修改，或选择“取消”以继续编辑XML。",

  /**Toolbox begin*/
  /** toolbox的开始 */
  id_start: "开始",
  /** toolbox的动作 */
  id_actions: "运动",
  /** toolbox的运动 */
  id_moves : "运动",
  /** toolbox的感知 */
  id_sensors : "感知",
  /** toolbox的事件 */
  id_events : "事件",
  /** toolbox的数学 */
  id_math : "数学",
   /** toolbox的控制 */
  id_control : "控制",
  /** toolbox的展示 */
  id_show : "展示",
  /**Toolbox end*/

  /**Start Category begin */
  id_when_start : "点击开始",
  id_go_to_start : "重新开始",
  /**Start Category end */
  
  /** Movement Category begin */
  servo_angle_popup_title :"设置舵机旋转角度",
  servo_angle_popup_close:"关闭",
  servo_angle_popup_variable:"变量",
  servo_angle_popup_angle:"角度",
  servo_angle_popup_cancel :"取消",
  servo_angle_popup_ok :"确定",

  rotate_servo_popup_clockwise:"顺时针",
  rotate_servo_popup_anti_clockwise:"逆时针",
  rotate_servo_popup_stop:"停止",
  rotate_servo_popup_title:"设置舵机旋转360度",
  rotate_servo_popup_cancel:"取消",
  rotate_servo_popup_ok:"确定",

  servo_status_popup_title:"设置舵机状态",
  servo_status_popup_cancel:"取消",
  servo_status_popup_ok:"确定",
  servo_status_popup_locking:"锁定",
  servo_status_popup_adjustable:"可调节",
  servo_status_popup_tips:"锁定状态时，不可调节机器人对应的舵机",

  posture_named_popup_title :"保存动作",
  posture_named_popup_cancel :"取消",
  posture_named_popup_ok :"确定",
  posture_named_popup_placeholder :"动作名称",
  posture_named_popup_msg :"动作名称包含非法字符",
  posture_named_too_long : "字数不能超过%1个汉字或%2个字符",

  gyro_rotate_direction_popup_title :"选择陀螺仪旋转方向",
  gyro_rotate_direction_popup_cancel :"取消",
  gyro_rotate_direction_popup_ok :"确定",
  gyro_rotate_direction_popup_curVal :"当前值",
  gyro_rotate_direction_popup_course :"航向角",
  gyro_rotate_direction_popup_horizontal :"横滚角",
  gyro_rotate_direction_popup_house :"俯仰角",

  posture_set_desc : "打开右边开关后可掰动机器人设置动作",
  posture_ok_desc : "摆好动作后可输入动作名称",

  id_servo : '设置舵机',
  id_rotate : '旋转',
  id_degree : '度',
  id_in : '时长',
  id_millsecond : '毫秒',

  id_rotate_circle : '旋转舵机360度',
  id_servos : '旋转舵机',
  id_run_to : '执行',

  id_all: '全部',
  id_lock : '锁定',
  id_unlock : '可调节',

  servo_id : 'ID',
  servo_angle : '角度', 
  movement_gesture: '动作',
  servo_direction : '方向',
  servo_speed : '速度',
  /** Movement Category end */

  /**Control Category begin */
  id_control_wait_for : '等待',
  id_control_repeat : '重复',
  id_control_repeat_times: '次',
  id_control_wait:'等待',
  id_control_seconds:'毫秒',
  id_math_not:'非',
  id_while : '当满足',
  id_until : '直到',
  id_repeat : '重复',
  /**Control Category end */

  /*Event Category begin*/
  maincontrol_box :"控制器",
  low_power :"模型电量低",
  ir_sensor : "红外传感器",
  reflectance : "距离",
  touch_sensor:"触碰传感器",
  status : "状态为",
  title_touch_sensor : "设置触碰传感器",
  click : "单击",
  db_click : "双击",
  press_hold : "长按",
  release : "松开",
  gyroscope : "陀螺仪",
  axie : '轴',
  title_device_tilt : "选择手机/平板状态",
  phone_pad :"手机/平板",
  tilt_left : "向左倾斜",
  tilt_right : "向右倾斜",
  tilt_up : "向上倾斜",
  tilt_down : "向下倾斜",
  tilt_swing : "左右摇晃",
  /*Event Category end*/

  /** Show Category start */
  id_show_play_effect:'播放音效',
  id_show_play_tune:'播放音调',
  id_show_show_emoji:'显示表情',
  id_show_show_LEDs:'显示灯光',
  id_show_time_during:'时长',
  id_show_time_ms:'毫秒',
  id_show_times:'次',
  sound_effects_popup_title :"设置音效",
  sound_effects_popup_cancel :"取消",
  sound_effects_popup_ok :"确定",
  sound_effects_recording_add :"新增录音",
  sound_effects_recording_delete :"删除",
  title_setting_light : "设置灯光",
  title_setting_tune : "设置音调",
  title_setting_emotion : "设置表情",
  id_all_bright: "全亮",
  id_custom: "自定义",
  id_smile: '微笑',
  id_cry : '哭泣',
  id_sad : '伤心',
  id_wink : '眨眼',
  id_dizzy : '晕',
  id_daze : '发呆',
  id_open_eyes : '睁眼',
  close_eyes : '闭眼',
  /** Show Category end */

  /**Sensor Category begin */
  id_sensor_IR_sensor: '红外传感器',
  id_sensor_reflectance_between_obstacle:'与障碍物距离',
  id_sensor_touch_sensor:'触碰传感器',
  id_sensor_touch_sensor_status:'状态',
  id_sensor_gyroscope:'陀螺仪',
  id_sensor_angle:'角度',
  x_axie:'横滚角',
  y_axie:'俯仰角',
  z_axie:'航向角',
  servo:'舵机',
  id_sensor_set_gyroscope:'设置 陀螺仪',
  id_sensor_angle_to_zero:'全部角度为0°',
  /**Sensor Category end */

  /**Math Category begin */
  id_math_variables_set_add : "%1 + %2",
  id_set : "设置",
  id_to : "为",
  /**Math Category end */

  /* Common section begin */
  btn_name_confirm : "确定",
  btn_name_cancel: "取消",
  /* Common section end*/

  
  id_start_info : '运行',
  id_stop_info : '停止',

  title_infrared_sensor : "设置红外传感器",
  current_value: '当前值',

  title_bluetooth_connect : "蓝牙连接",
  title_time_adjust : "设置时长",

  index_back:"返回",
  disconnected : "未连接",

/*项目  begin*/
  //保存项目
  input_rule_msg : "特殊字符无法输入，最多输入%1个字符或%2个汉字",
  variable_inputrule_msg : "不能以数字开头，特殊字符无法输入，最多输入%1个字符或%2个汉字",
  add_project_placeholder : "项目名称",
  project_pop_ok_btn: "确定",
  project_pop_cancel_btn: "取消",
  add_project_pop_title : "保存项目",
  add_project_input_check : "只能输入16个字符",
  project_name_too_long : "字数不超过%1个汉字或%2个字符",
  project_name_popup_msg : "项目名称包含非法字符",
  //是否保存项目
  is_add_project_pop_title :"保存项目",
  is_add_project_pop_tips :"是否保存当前项目",
  //项目列表
  project_list_title :"我的项目",

  //保存项目
  porject_alert_title:"错误",
  porject_alert_tips:"提示",
  porject_alert_content:"对不起，操作对象参数不正确，请检查！",
  porject_alert_content_01:"对不起，你输入的项目名称已经被使用！",
  porject_alert_content_02:"底层业务操作有误，错误信息为：",
  porject_alert_content_03:"底层返回数据有误！",
  porject_alert_content_04:"项目文件读取有误",
  porject_alert_content_05:"对不起，读取的项目文件中含有错误的程序块内容！",
  porject_alert_content_06:"项目保存成功",
  porject_alert_btnText:"确定",
 
  add_recording_ok:"完成",
  recording_tips:"录音中",

  id_control_break : '跳出循环',
  
  id_blue_disconnect : '未连接蓝牙',
  id_ok : '确定',

  recording_title:"录音中",
  recording_cancel:"取消",
  recording_ok:"完成",
  recording_placeholder:"录音名称",
  recording_popup_title:"保存录音",
  recording_name_popup_msg : "录音名称包含非法字符",
 /*项目  end*/
    /*设置音效弹出框音效文件国际化  begin*/
    animal:"动物",
    machine:"机器",
    recording:"录音",
    bear:"熊",
    bird:"鸟",
    chicken:"鸡",
    cow:"牛",
    dog:"狗",
    elephant:"大象",
    giraffe:"长颈鹿",
    horse:"马",
    lion:"狮子",
    monkey:"猴子",
    pig:"猪",
    rhinoceros:"犀牛",
    sealions:"海狮",
    tiger:"老虎",
    walrus:"海象",
    ambulance:"救护车",
    busy_tone:"忙音",
    carhorn:"汽车喇叭",
    carhorn1:"汽车喇叭1",
    doorbell:"门铃",
    engine:"引擎",
    laser:"激光",
    meebot:"小黄人",
    police_car_1:"警车1",
    police_car_2:"警车2",
    ringtones:"来电铃声",
    robot:"机器人",
    telephone_call:"电话呼叫",
    touch_tone:"按键音",
    wave:"电波",
    /*设置音效弹出框音效文件国际化  end*/

 variable_named_popup_placeholder :"变量名",
 title_variable_set : '设置变量',
 variable_named_popup_msg :"以字母或下划线开头，由数字、字母、下划线组成",
 variable_named_too_long : "字数不能超过%1个汉字或%2个字符",
    speed:"速度",
    speed_VS:"非常慢",
    speed_S:"慢速",
    speed_M:"中速",
    speed_V:"快速",
    speed_VF:"非常快",
    speed_no_value:"模型中没有可以360°旋转的舵机",
    speed_only_360_value:"模型中没有普通角度舵机",
    exit_tips:"当前程序未保存，是否继续退出？",
    lights_tips:"当前模型未连接灯光",
    project_has_no_change:"当前程序未改动",
    close_blue:"蓝牙处于连接状态，是否关闭?",
    posture_link:"模型未连接，请先连接模型",
    posture_link_popup_title:"模型连接",
    posture_link_popup_cancel:"取消",
    posture_link_popup_ok:"确定",
    recording_name_repeat:"录音名称已存在",
    recording_named_too_long : "字数不能超过%1个汉字或%2个字符",
    recording_alert_title:"错误提示",
    recording_alert_content:"录音授权失败",
    recording_alert_ok:"确定",
    help_title:"程序块介绍",
    newProjectName:"新项目",
    sysVoiceName:"新录音",
    exit_popup_cancel:"取消",
    exit_popup_ok:"确定",
    exit_popup_title:"提示",
    recording_data_tips:"暂无录音",
    infrared_tips:"当前模型未连接红外传感器",
    touch_tips:"当前模型未连接触碰传感器",
    gyroscope_tips:"当前模型未连接陀螺仪传感器",
    id_infinite_loop_error:"内存即将耗尽，请返回后重试。",

    // 新手指引 
    save_project_msg:"保存你的程序点击这里！",
    projectlist_msg:"查看Jimu已学会的程序，并为他建立新程序！",
    swift_msg:"查看swift代码，点击这里！",
    help_msg:"有疑问的时候点击这里！",
    run_msg:"让Jimu按你的程序运动起来！",
    go_skip:"跳过",
    servo_mode_error : '舵机模式错误',
    set_servo_mode : '设置',
    id_show_scenelight:'显示情景灯',
    title_setting_scenelight : "设置情景灯",
    id_happy:"开心",
    id_jingya:"惊讶",    
    id_relei:"热泪盈眶",
    id_leiguang:"泪光闪动",
    id_shangxin:"伤心",
    id_yun:"晕",
    id_fadai:"发呆",
    id_zhayan:"眨眼",
    id_haixiu:"害羞",
    id_shanshuo:"闪烁",
    id_huxi:"呼吸",
    id_fengshan:"风扇",
    id_yugua:"雨刮",

    id_deng:"七彩跑马灯",
    id_disco:"Disco",
    id_caise:"彩色堆叠",
    id_sanyuanse:"三原色",
    select_all:"全选",
    no_common_servo_info : "您的积木无角度模式舵机，是否需要设置",
    no_circle_servo_info : "您的积木无轮模式舵机，是否需要设置"
};
